name: iridescentangle
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^0.2.3
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.0+2
  # webview 据说更好用一些
  webview_flutter : ^0.2.0
  # 工具集
  common_utils: ^1.0.9
  # 微信分享
  fluwx : ^0.6.0
  # 显示未读消息数的控件
  # badge : ^0.0.3
  # SharedPreference：
  shared_preferences : ^0.4.3
  # Toast
  fluttertoast: ^2.2.6
  # 工具包
  flustars: ^0.2.4
  # 轮播图
  flutter_swiper: ^1.1.4
  # 拼音库
  lpinyin: ^1.0.7
  # dio网络请求库
  dio : ^1.0.13
  # 超链接
  url_launcher : ^ 4.0.3
  # 调用图库和相机
  image_picker : ^ 0.4.12+1
  # 快速检索列表
  azlistview: ^0.1.0
  # 极光推送
  jpush_flutter: ^0.0.11
  # 屏幕适配
  flutter_screenutil : ^0.5.1
  # redux状态管理
  flutter_redux: ^0.5.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.9.0
  json_serializable: ^0.5.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/china.json
    # - assets/images/beijing.jpg
  # fonts:
  #   - family : appIconFonts
  #     fonts :
  #       - asset: iconfont/iconfont.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
